name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install libpipewire-0.3-dev

      - name: Build binary
        run: cargo build --release
